[build]
  command = "npm run netlify-build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NITRO_PRESET = "netlify"
  # 确保 Prisma 客户端在构建时生成
  PRISMA_CLI_BINARY_TARGETS = "debian-openssl-1.1.x,rhel-openssl-1.0.x,linux-musl"
  PRISMA_GENERATE_SKIP_AUTOINSTALL = "false"

[functions]
  directory = ".netlify/functions-internal"
  node_bundler = "esbuild"
  # 增加内存限制和超时时间
  [functions."server"]
    included_files = ["node_modules/@prisma/client/**/*", "prisma/**/*"]
    external_node_modules = []
    node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[template.environment]
  DATABASE_URL = "PostgreSQL数据库连接字符串，格式如：postgresql://username:password@host:port/database?sslmode=require"
  JWT_SECRET = "JWT令牌签名密钥，建议使用强随机字符串"
  NUXT_PUBLIC_SITE_TITLE = "站点标题，默认为'班级多媒体点播系统'"
  NUXT_PUBLIC_SITE_LOGO = "站点Logo URL，可选"
  NUXT_PUBLIC_SITE_DESCRIPTION = "站点描述，可选"